const PressReleasePage = () => {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <header className="mb-8 space-y-2 py-4">
        <h1 className="text-3xl md:text-4xl font-header font-bold font-stretch-200% tracking-tight">Press Release</h1>
      </header>

      <main className="prose prose-slate max-w-none">
        <p className="font-content tracking-wider text-sm md:text-base leading-8 font-bold">
          Tysons Advisory, LLC Assessed “Awardable” for Department of Defense work in the CDAO’s Tradewinds Solutions Marketplace
        </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">McLean, VA – Apr 2nd, 2025 – Tysons Advisory, LLC, a premier provider of strategy, advisory, automation, and systems implementation services, is pleased to announce that it has achieved “Awardable” status through the Chief Digital and Artificial Intelligence Office’s (CDAO) Tradewinds Solutions Marketplace. This recognition places Tysons Advisory among an elite group of companies whose solutions have been deemed impactful and highly relevant to mission-critical operations for both government and industry. </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">The Tradewinds Solutions Marketplace is the premier offering of Tradewinds, the Department of Defense’s (DoD’s) suite of tools and services designed to accelerate the procurement and adoption of Artificial Intelligence (AI)/Machine Learning (ML), data, and analytics capabilities.  </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">Tysons Advisory’s solutions are designed to address the three biggest challenges in organizations - limited access to data, a shortage of skilled professionals with the necessary credentials to build trust with data owners and business, and the need for effective AI model training and integrated technology capabilities on the edge. “Achieving ‘Awardable’ status on the Tradewinds Solutions Marketplace is a significant milestone that reflects our steadfast commitment to national security and operational excellence,” said Aditi Charnoubi, Managing Partner at Tysons Advisory. “This reinforces the strategic value of our Real-Time AI Inferencing on the Edge platform, developed in close collaboration with our industry and government partners. By integrating high-performance storage and AI inference into a compact, low SWaP (size, weight, and power) and supporting custom built analytics and AI models, we enable rapid, secure, and mission-ready AI capabilities for tactical edge operations, mobile deployments, remote locations, and headquarters. Our solution facilitates petabyte-scale data mobility, allowing commanders and operators to make faster, intelligence-driven decisions in austere and contested environments. We are committed to support our federal partners in executing their most complex and high-stakes missions with precision and reliability.” </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">Tysons Advisory’s video, “Revolutionizing Mobile, Secure, AI Driven Data Solutions from Edge to Back Office with BRYCK AI” is accessible only by government customers on the Tradewinds Solutions Marketplace.  </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">Tysons Advisory was recognized among a competitive field of applicants to the Tradewinds Solutions Marketplace whose solutions demonstrated innovation, scalability, and potential impact on DoD missions. Government customers interested in viewing the video solution can create a Tradewinds Solutions Marketplace account at tradewindAI.com.  </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">Others interested in Tysons Advisory’s solution and partnering opportunities for government or commercial GTM, please reach out directly to Tysons Advisory. </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">About Tysons Advisory: Leading with trust, innovation and industry best practices, Tysons Advisory&apos;s team of subject matter experts and experienced technologists deliver mission-critical projects to bring about transformation and modernization of people, process and technology for enterprise and government. With services spanning Strategy, Program Management, Data and Analytics, RPA and Real Time AI Inferencing on the Edge, we empower our clients to tackle today’s challenges and lead in tomorrow’s ever-evolving landscape. For more information or media requests, contact: info@tysonsadvisory.com </p>
        <p className="font-content tracking-wider text-sm md:text-base leading-8 pb-5">About the Tradewinds Solutions Marketplace: The Tradewinds Solutions Marketplace is a digital repository of post-competition, readily awardable pitch videos that address the Department of Defense’s (DoD) most significant challenges in the Artificial Intelligence/ Machine Learning (AI/ML), data, and analytics space. All awardable solutions have been assessed through complex scoring rubrics and competitive procedures and are available to Government customers with a Marketplace account. Government customers can create an account at www.tradewindai.com. Tradewinds is housed in the DoD’s Chief Digital Artificial Intelligence Office. For more information or media requests, contact: Success@tradewindai.com </p>
      </main>
    </div>
  );
};

export default PressReleasePage;

